-- GET MALAYSIA COMPANY STOCK ORDINARY SHARES
SELECT * FROM EQUITY_SECURITY WHERE (SEC_CLASSIF_CODE = 'ORD' AND PRIMARY_STOCK_EXCHG_ALPHA_CODE IN ('MYS00', 'MYS01', 'MYS02'))

-- GET THE TICKER OF THOSE STOCKS
SELECT EQUITY_SECURITY.COMPANY_PERM_ID, CROSS_REF.mic, CROSS_REF.TICKER, CROSS_REF.COMPANY_NAME
FROM CROSS_REF JOIN
EQUITY_SECURITY ON
CROSS_REF.EQUITY_SEC_PERM_ID = EQUITY_SECURITY.EQUITY_SEC_PERM_ID
WHERE (EQUITY_SECURITY.SEC_CLASSIF_CODE = 'ORD' AND EQUITY_SECURITY.PRIMARY_STOCK_EXCHG_ALPHA_CODE IN ('MYS00', 'MYS01', 'MYS02') AND CROSS_REF.MIC = 'XKLS')

SELECT *
FROM CROSS_REF JOIN
EQUITY_SECURITY ON
CROSS_REF.EQUITY_SEC_PERM_ID = EQUITY_SECURITY.EQUITY_SEC_PERM_ID
WHERE (EQUITY_SECURITY.SEC_CLASSIF_CODE = 'ORD' AND EQUITY_SECURITY.PRIMARY_STOCK_EXCHG_ALPHA_CODE IN ('MYS00', 'MYS01', 'MYS02') AND CROSS_REF.MIC = 'XKLS')


-- JOIN WITH SYARIAH TO GET LARGEST HDR_PERM_ID
SELECT SHARIAH_COMPLIANCE.COMPANY_PERM_ID, MAX(SHARIAH_COMPLIANCE.WVB_CO_FIN_DATA_HDR_PERM_ID) AS MX_HDR_ID FROM
SHARIAH_COMPLIANCE JOIN 
(
SELECT EQUITY_SECURITY.COMPANY_PERM_ID, CROSS_REF.mic, CROSS_REF.TICKER, CROSS_REF.COMPANY_NAME
FROM CROSS_REF JOIN
EQUITY_SECURITY ON
CROSS_REF.EQUITY_SEC_PERM_ID = EQUITY_SECURITY.EQUITY_SEC_PERM_ID
WHERE (EQUITY_SECURITY.SEC_CLASSIF_CODE = 'ORD' AND EQUITY_SECURITY.PRIMARY_STOCK_EXCHG_ALPHA_CODE IN ('MYS00', 'MYS01', 'MYS02') AND CROSS_REF.MIC = 'XKLS')
) MY_STOCK ON
SHARIAH_COMPLIANCE.COMPANY_PERM_ID = MY_STOCK.COMPANY_PERM_ID
GROUP BY
SHARIAH_COMPLIANCE.COMPANY_PERM_ID;

-- JOIN WITH WVB_COMPANY_FIN_DATA_HDR TO GET THE REPORT DATE
SELECT MX_HDR.COMPANY_PERM_ID, MX_HDR.MX_HDR_ID, WVB_COMPANY_FIN_DATA_HDR.FISCAL_PERIOD_END_DATE, MX_HDR.TICKER, MX_HDR.COMPANY_NAME
FROM
WVB_COMPANY_FIN_DATA_HDR JOIN
(
SELECT SHARIAH_COMPLIANCE.COMPANY_PERM_ID, MAX(SHARIAH_COMPLIANCE.WVB_CO_FIN_DATA_HDR_PERM_ID) AS MX_HDR_ID, MY_STOCK.TICKER, MY_STOCK.COMPANY_NAME
FROM
SHARIAH_COMPLIANCE JOIN 
(
SELECT EQUITY_SECURITY.COMPANY_PERM_ID, CROSS_REF.mic, CROSS_REF.TICKER, CROSS_REF.COMPANY_NAME
FROM CROSS_REF JOIN
EQUITY_SECURITY ON
CROSS_REF.EQUITY_SEC_PERM_ID = EQUITY_SECURITY.EQUITY_SEC_PERM_ID
WHERE (EQUITY_SECURITY.SEC_CLASSIF_CODE = 'ORD' AND EQUITY_SECURITY.PRIMARY_STOCK_EXCHG_ALPHA_CODE IN ('MYS00', 'MYS01', 'MYS02') AND CROSS_REF.MIC = 'XKLS' AND LENGTH(TICKER) IN (4,5))
) MY_STOCK ON
SHARIAH_COMPLIANCE.COMPANY_PERM_ID = MY_STOCK.COMPANY_PERM_ID
GROUP BY
SHARIAH_COMPLIANCE.COMPANY_PERM_ID, MY_STOCK.TICKER, MY_STOCK.COMPANY_NAME
) MX_HDR ON
WVB_COMPANY_FIN_DATA_HDR.WVB_CO_FIN_DATA_HDR_PERM_ID = MX_HDR.MX_HDR_ID;


-- JOIN IT BACK TO SYARIAH_COMPLIANCE TABLE TO GET ALL SYARIAH DATA
SELECT SHARIAH_COMPLIANCE.COMPANY_PERM_ID, LATEST_REPORT.TICKER, LATEST_REPORT.COMPANY_NAME, LATEST_REPORT.FISCAL_PERIOD_END_DATE, SHARIAH_COMPLIANCE.HARAM_STATUS, SHARIAH_COMPLIANCE.DEBT_ASSET_RATIO, 
SHARIAH_COMPLIANCE.DEBT_ASSET_RATIO_2ND, SHARIAH_COMPLIANCE.CASH_INTEREST_ASSET_RATIO, SHARIAH_COMPLIANCE.CASH_INTEREST_ASSET_RATIO_2ND, SHARIAH_COMPLIANCE.NON_SHARIA_SUBS_RATIO, SHARIAH_COMPLIANCE.CASH_AR_RATIO,
SHARIAH_COMPLIANCE.CASH_AR_RATIO_2ND, SHARIAH_COMPLIANCE.INTEREST_INCOME_ASSET_RATIO, SHARIAH_COMPLIANCE.NON_SHARIA_SUBS_INT_RATIO, SHARIAH_COMPLIANCE.DEBT_MCAP_RATIO, SHARIAH_COMPLIANCE.CASH_INTEREST_MCAP_RATIO,
SHARIAH_COMPLIANCE.CASH_AR_MCAP_RATIO, SHARIAH_COMPLIANCE.SHARIAH_SCORE, SHARIAH_COMPLIANCE.SHARIAH_SCORE_2ND 
FROM 
SHARIAH_COMPLIANCE JOIN
(
SELECT MX_HDR.COMPANY_PERM_ID, MX_HDR.MX_HDR_ID, WVB_COMPANY_FIN_DATA_HDR.FISCAL_PERIOD_END_DATE, MX_HDR.TICKER, MX_HDR.COMPANY_NAME
FROM
WVB_COMPANY_FIN_DATA_HDR JOIN
(
SELECT SHARIAH_COMPLIANCE.COMPANY_PERM_ID, MAX(SHARIAH_COMPLIANCE.WVB_CO_FIN_DATA_HDR_PERM_ID) AS MX_HDR_ID, MY_STOCK.TICKER, MY_STOCK.COMPANY_NAME
FROM
SHARIAH_COMPLIANCE JOIN 
(
SELECT EQUITY_SECURITY.COMPANY_PERM_ID, CROSS_REF.mic, CROSS_REF.TICKER, CROSS_REF.COMPANY_NAME
FROM CROSS_REF JOIN
EQUITY_SECURITY ON
CROSS_REF.EQUITY_SEC_PERM_ID = EQUITY_SECURITY.EQUITY_SEC_PERM_ID
WHERE (EQUITY_SECURITY.SEC_CLASSIF_CODE = 'ORD' AND EQUITY_SECURITY.PRIMARY_STOCK_EXCHG_ALPHA_CODE IN ('MYS00', 'MYS01', 'MYS02') AND CROSS_REF.MIC = 'XKLS' AND LENGTH(TICKER) IN (4,5))
) MY_STOCK ON
SHARIAH_COMPLIANCE.COMPANY_PERM_ID = MY_STOCK.COMPANY_PERM_ID
GROUP BY
SHARIAH_COMPLIANCE.COMPANY_PERM_ID, MY_STOCK.TICKER, MY_STOCK.COMPANY_NAME
) MX_HDR ON
WVB_COMPANY_FIN_DATA_HDR.WVB_CO_FIN_DATA_HDR_PERM_ID = MX_HDR.MX_HDR_ID
) LATEST_REPORT ON
SHARIAH_COMPLIANCE.WVB_CO_FIN_DATA_HDR_PERM_ID = LATEST_REPORT.MX_HDR_ID;

SELECT * FROM CROSS_REF WHERE TICKER = '9954'