--==================
--BROKER_RANK_WTD
--==================

drop table dibots_v2.broker_rank_wtd;
create table dibots_v2.broker_rank_wtd (
trading_date date,
week_count varchar(10),
external_id int,
participant_code int,
participant_name varchar(255),
wtd_day_count int,
wtd_total_vol bigint,
wtd_total_val numeric(32,5),
wtd_total_pct numeric(10,2),
wtd_total_rank int,
wtd_local_vol bigint,
wtd_local_val numeric(32,5),
wtd_local_pct numeric(10,2),
wtd_local_rank int,
wtd_foreign_vol bigint,
wtd_foreign_val numeric(32,5),
wtd_foreign_pct numeric(10,2),
wtd_foreign_rank int,
wtd_nominee_total_vol bigint,
wtd_nominee_total_val numeric(32,5),
wtd_nominee_total_pct numeric(10,2),
wtd_nominee_total_rank int,
wtd_nominee_local_vol bigint,
wtd_nominee_local_val numeric(32,5),
wtd_nominee_local_pct numeric(10,2),
wtd_nominee_local_rank int,
wtd_nominee_foreign_vol bigint,
wtd_nominee_foreign_val numeric(32,5),
wtd_nominee_foreign_pct numeric(10,2),
wtd_nominee_foreign_rank int,
wtd_inst_total_vol bigint,
wtd_inst_total_val numeric(32,5),
wtd_inst_total_pct numeric(10,2),
wtd_inst_total_rank int,
wtd_inst_local_vol bigint,
wtd_inst_local_val numeric(32,5),
wtd_inst_local_pct numeric(10,2),
wtd_inst_local_rank int,
wtd_inst_foreign_vol bigint,
wtd_inst_foreign_val numeric(32,5),
wtd_inst_foreign_pct numeric(10,2),
wtd_inst_foreign_rank int,
wtd_retail_total_vol bigint,
wtd_retail_total_val numeric(32,5),
wtd_retail_total_pct numeric(10,2),
wtd_retail_total_rank int,
wtd_retail_local_vol bigint,
wtd_retail_local_val numeric(32,5),
wtd_retail_local_pct numeric(10,2),
wtd_retail_local_rank int,
wtd_retail_foreign_vol bigint,
wtd_retail_foreign_val numeric(32,5),
wtd_retail_foreign_pct numeric(10,2),
wtd_retail_foreign_rank int,
wtd_proprietary_vol bigint,
wtd_proprietary_val numeric(32,5),
wtd_proprietary_pct numeric(10,2),
wtd_proprietary_rank int,
wtd_ivt_vol bigint,
wtd_ivt_val numeric(32,5),
wtd_ivt_pct numeric(10,2),
wtd_ivt_rank int,
wtd_pdt_vol bigint,
wtd_pdt_val numeric(32,5),
wtd_pdt_pct numeric(10,2),
wtd_pdt_rank int,
wtd_market_algo_cnt numeric(32,5),
wtd_algo_cnt numeric(32,5),
wtd_algo_pct numeric(10,2),
wtd_algo_rank int,
wtd_inet_cnt numeric(32,5),
wtd_inet_pct numeric(10,2),
wtd_inet_rank int,
wtd_dma_cnt numeric(32,5),
wtd_dma_pct numeric(10,2),
wtd_dma_rank int,
wtd_brok_cnt numeric(32,5),
wtd_brok_pct numeric(10,2),
wtd_brok_rank int,
wtd_ord_cnt bigint,
wtd_trd_cnt bigint,
wtd_ot_ratio numeric(10,2),
buy_vol bigint,
buy_val numeric(32,5),
sell_vol bigint,
sell_val numeric(32,5)
);

alter table dibots_v2.broker_rank_wtd add constraint broker_rank_wtd_pkey primary key (trading_date, participant_code);

create index broker_rank_wtd_ext_id_idx on dibots_v2.broker_rank_wtd (external_id);

insert into dibots_v2.broker_rank_wtd (trading_date, week_count, external_id, participant_code, participant_name, wtd_day_count, wtd_total_vol, wtd_total_val, wtd_total_pct, wtd_total_rank, 
wtd_local_vol, wtd_local_val, wtd_local_pct, wtd_local_rank, 
wtd_foreign_vol, wtd_foreign_val, wtd_foreign_pct, wtd_foreign_rank, 
wtd_nominee_total_vol, wtd_nominee_total_val, wtd_nominee_total_pct, wtd_nominee_total_rank, 
wtd_nominee_local_vol, wtd_nominee_local_val, wtd_nominee_local_pct, wtd_nominee_local_rank, 
wtd_nominee_foreign_vol, wtd_nominee_foreign_val, wtd_nominee_foreign_pct, wtd_nominee_foreign_rank, 
wtd_inst_total_vol, wtd_inst_total_val, wtd_inst_total_pct, wtd_inst_total_rank, 
wtd_inst_local_vol, wtd_inst_local_val, wtd_inst_local_pct, wtd_inst_local_rank, 
wtd_inst_foreign_vol, wtd_inst_foreign_val, wtd_inst_foreign_pct, wtd_inst_foreign_rank, 
wtd_retail_total_vol, wtd_retail_total_val, wtd_retail_total_pct, wtd_retail_total_rank, 
wtd_retail_local_vol, wtd_retail_local_val, wtd_retail_local_pct, wtd_retail_local_rank, 
wtd_retail_foreign_vol, wtd_retail_foreign_val, wtd_retail_foreign_pct, wtd_retail_foreign_rank, 
wtd_proprietary_vol, wtd_proprietary_val, wtd_proprietary_pct, wtd_proprietary_rank, 
wtd_ivt_vol, wtd_ivt_val, wtd_ivt_pct, wtd_ivt_rank, 
wtd_pdt_vol, wtd_pdt_val, wtd_pdt_pct, wtd_pdt_rank)
select trading_date, week_count, external_id, participant_code, participant_name, 1, total_trade_volume, total_trade_value, total_pct, rank_total,
local_trade_volume, local_trade_value, local_pct, rank_local,
foreign_trade_volume, foreign_trade_value, foreign_pct, rank_foreign,
nominee_total_trade_volume, nominee_total_trade_value, nominee_total_pct, rank_nominee_total,
nominee_local_trade_volume, nominee_local_trade_value, nominee_local_pct, rank_nominee_local,
nominee_foreign_trade_volume, nominee_foreign_trade_value, nominee_foreign_pct, rank_nominee_foreign,
inst_total_trade_volume, inst_total_trade_value, inst_total_pct, rank_inst_total,
inst_local_trade_volume, inst_local_trade_value, inst_local_pct, rank_inst_local,
inst_foreign_trade_volume, inst_foreign_trade_value, inst_foreign_pct, rank_inst_foreign,
retail_total_trade_volume, retail_total_trade_value, retail_total_pct, rank_retail_total,
retail_local_trade_volume, retail_local_trade_value, retail_local_pct, rank_retail_local,
retail_foreign_trade_volume, retail_foreign_trade_value, retail_foreign_pct, rank_retail_foreign,
proprietary_trade_volume, proprietary_trade_value, proprietary_pct, rank_proprietary,
ivt_trade_volume, ivt_trade_value, ivt_pct, rank_ivt,
pdt_trade_volume, pdt_trade_value, pdt_pct, rank_pdt
from dibots_v2.broker_rank_day
where trading_date = '2017-05-02'

select * from dibots_v2.broker_rank_wtd order by trading_date desc

select * from dibots_v2.broker_rank_day order by trading_date desc


--===================
--BROKER_RANK_MTD
--===================

drop table dibots_v2.broker_rank_mtd;
create table dibots_v2.broker_rank_mtd (
trading_date date,
year int,
month int,
external_id int,
participant_code int,
participant_name varchar(255),
mtd_day_count int,
mtd_total_vol bigint,
mtd_total_val numeric(32,5),
mtd_total_pct numeric(10,2),
mtd_total_rank int,
mtd_local_vol bigint,
mtd_local_val numeric(32,5),
mtd_local_pct numeric(10,2),
mtd_local_rank int,
mtd_foreign_vol bigint,
mtd_foreign_val numeric(32,5),
mtd_foreign_pct numeric(10,2),
mtd_foreign_rank int,
mtd_nominee_total_vol bigint,
mtd_nominee_total_val numeric(32,5),
mtd_nominee_total_pct numeric(10,2),
mtd_nominee_total_rank int,
mtd_nominee_local_vol bigint,
mtd_nominee_local_val numeric(32,5),
mtd_nominee_local_pct numeric(10,2),
mtd_nominee_local_rank int,
mtd_nominee_foreign_vol bigint,
mtd_nominee_foreign_val numeric(32,5),
mtd_nominee_foreign_pct numeric(10,2),
mtd_nominee_foreign_rank int,
mtd_inst_total_vol bigint,
mtd_inst_total_val numeric(32,5),
mtd_inst_total_pct numeric(10,2),
mtd_inst_total_rank int,
mtd_inst_local_vol bigint,
mtd_inst_local_val numeric(32,5),
mtd_inst_local_pct numeric(10,2),
mtd_inst_local_rank int,
mtd_inst_foreign_vol bigint,
mtd_inst_foreign_val numeric(32,5),
mtd_inst_foreign_pct numeric(10,2),
mtd_inst_foreign_rank int,
mtd_retail_total_vol bigint,
mtd_retail_total_val numeric(32,5),
mtd_retail_total_pct numeric(10,2),
mtd_retail_total_rank int,
mtd_retail_local_vol bigint,
mtd_retail_local_val numeric(32,5),
mtd_retail_local_pct numeric(10,2),
mtd_retail_local_rank int,
mtd_retail_foreign_vol bigint,
mtd_retail_foreign_val numeric(32,5),
mtd_retail_foreign_pct numeric(10,2),
mtd_retail_foreign_rank int,
mtd_proprietary_vol bigint,
mtd_proprietary_val numeric(32,5),
mtd_proprietary_pct numeric(10,2),
mtd_proprietary_rank int,
mtd_ivt_vol bigint,
mtd_ivt_val numeric(32,5),
mtd_ivt_pct numeric(10,2),
mtd_ivt_rank int,
mtd_pdt_vol bigint,
mtd_pdt_val numeric(32,5),
mtd_pdt_pct numeric(10,2),
mtd_pdt_rank int,
mtd_market_algo_cnt numeric(32,5),
mtd_algo_cnt numeric(32,5),
mtd_algo_pct numeric(10,2),
mtd_algo_rank int,
mtd_inet_cnt numeric(32,5),
mtd_inet_pct numeric(10,2),
mtd_inet_rank int,
mtd_dma_cnt numeric(32,5),
mtd_dma_pct numeric(10,2),
mtd_dma_rank int,
mtd_brok_cnt numeric(32,5),
mtd_brok_pct numeric(10,2),
mtd_brok_rank int,
mtd_ord_cnt bigint,
mtd_trd_cnt bigint,
mtd_ot_ratio numeric(10,2),
buy_vol bigint,
buy_val numeric(32,5),
sell_vol bigint,
sell_val numeric(32,5)
);

alter table dibots_v2.broker_rank_mtd add constraint broker_rank_mtd_pkey primary key (trading_date, participant_code);

create index broker_rank_mtd_ext_id_idx on dibots_v2.broker_rank_mtd(external_id);

select * from dibots_v2.broker_rank_mtd order by trading_date

insert into dibots_v2.broker_rank_mtd (trading_date, year, month, external_id, participant_code, participant_name, mtd_day_count, mtd_total_vol, mtd_total_val, mtd_total_pct, mtd_total_rank, 
mtd_local_vol, mtd_local_val, mtd_local_pct, mtd_local_rank, 
mtd_foreign_vol, mtd_foreign_val, mtd_foreign_pct, mtd_foreign_rank, 
mtd_nominee_total_vol, mtd_nominee_total_val, mtd_nominee_total_pct, mtd_nominee_total_rank, 
mtd_nominee_local_vol, mtd_nominee_local_val, mtd_nominee_local_pct, mtd_nominee_local_rank, 
mtd_nominee_foreign_vol, mtd_nominee_foreign_val, mtd_nominee_foreign_pct, mtd_nominee_foreign_rank, 
mtd_inst_total_vol, mtd_inst_total_val, mtd_inst_total_pct, mtd_inst_total_rank, 
mtd_inst_local_vol, mtd_inst_local_val, mtd_inst_local_pct, mtd_inst_local_rank, 
mtd_inst_foreign_vol, mtd_inst_foreign_val, mtd_inst_foreign_pct, mtd_inst_foreign_rank, 
mtd_retail_total_vol, mtd_retail_total_val, mtd_retail_total_pct, mtd_retail_total_rank, 
mtd_retail_local_vol, mtd_retail_local_val, mtd_retail_local_pct, mtd_retail_local_rank, 
mtd_retail_foreign_vol, mtd_retail_foreign_val, mtd_retail_foreign_pct, mtd_retail_foreign_rank, 
mtd_proprietary_vol, mtd_proprietary_val, mtd_proprietary_pct, mtd_proprietary_rank, 
mtd_ivt_vol, mtd_ivt_val, mtd_ivt_pct, mtd_ivt_rank, 
mtd_pdt_vol, mtd_pdt_val, mtd_pdt_pct, mtd_pdt_rank)
select trading_date, year, month, external_id, participant_code, participant_name, 1, total_trade_volume, total_trade_value, total_pct, rank_total,
local_trade_volume, local_trade_value, local_pct, rank_local,
foreign_trade_volume, foreign_trade_value, foreign_pct, rank_foreign,
nominee_total_trade_volume, nominee_total_trade_value, nominee_total_pct, rank_nominee_total,
nominee_local_trade_volume, nominee_local_trade_value, nominee_local_pct, rank_nominee_local,
nominee_foreign_trade_volume, nominee_foreign_trade_value, nominee_foreign_pct, rank_nominee_foreign,
inst_total_trade_volume, inst_total_trade_value, inst_total_pct, rank_inst_total,
inst_local_trade_volume, inst_local_trade_value, inst_local_pct, rank_inst_local,
inst_foreign_trade_volume, inst_foreign_trade_value, inst_foreign_pct, rank_inst_foreign,
retail_total_trade_volume, retail_total_trade_value, retail_total_pct, rank_retail_total,
retail_local_trade_volume, retail_local_trade_value, retail_local_pct, rank_retail_local,
retail_foreign_trade_volume, retail_foreign_trade_value, retail_foreign_pct, rank_retail_foreign,
proprietary_trade_volume, proprietary_trade_value, proprietary_pct, rank_proprietary,
ivt_trade_volume, ivt_trade_value, ivt_pct, rank_ivt,
pdt_trade_volume, pdt_trade_value, pdt_pct, rank_pdt
from dibots_v2.broker_rank_day
where trading_date = '2017-05-02'


--==================
--BROKER_RANK_QTD
--==================

drop table dibots_v2.broker_rank_qtd;
create table dibots_v2.broker_rank_qtd (
trading_date date,
year int,
month int,
qtr int,
external_id int,
participant_code int,
participant_name varchar(255),
qtd_day_count int,
qtd_total_vol bigint,
qtd_total_val numeric(32,5),
qtd_total_pct numeric(10,2),
qtd_total_rank int,
qtd_local_vol bigint,
qtd_local_val numeric(32,5),
qtd_local_pct numeric(10,2),
qtd_local_rank int,
qtd_foreign_vol bigint,
qtd_foreign_val numeric(32,5),
qtd_foreign_pct numeric(10,2),
qtd_foreign_rank int,
qtd_nominee_total_vol bigint,
qtd_nominee_total_val numeric(32,5),
qtd_nominee_total_pct numeric(10,2),
qtd_nominee_total_rank int,
qtd_nominee_local_vol bigint,
qtd_nominee_local_val numeric(32,5),
qtd_nominee_local_pct numeric(10,2),
qtd_nominee_local_rank int,
qtd_nominee_foreign_vol bigint,
qtd_nominee_foreign_val numeric(32,5),
qtd_nominee_foreign_pct numeric(10,2),
qtd_nominee_foreign_rank int,
qtd_inst_total_vol bigint,
qtd_inst_total_val numeric(32,5),
qtd_inst_total_pct numeric(10,2),
qtd_inst_total_rank int,
qtd_inst_local_vol bigint,
qtd_inst_local_val numeric(32,5),
qtd_inst_local_pct numeric(10,2),
qtd_inst_local_rank int,
qtd_inst_foreign_vol bigint,
qtd_inst_foreign_val numeric(32,5),
qtd_inst_foreign_pct numeric(10,2),
qtd_inst_foreign_rank int,
qtd_retail_total_vol bigint,
qtd_retail_total_val numeric(32,5),
qtd_retail_total_pct numeric(10,2),
qtd_retail_total_rank int,
qtd_retail_local_vol bigint,
qtd_retail_local_val numeric(32,5),
qtd_retail_local_pct numeric(10,2),
qtd_retail_local_rank int,
qtd_retail_foreign_vol bigint,
qtd_retail_foreign_val numeric(32,5),
qtd_retail_foreign_pct numeric(10,2),
qtd_retail_foreign_rank int,
qtd_proprietary_vol bigint,
qtd_proprietary_val numeric(32,5),
qtd_proprietary_pct numeric(10,2),
qtd_proprietary_rank int,
qtd_ivt_vol bigint,
qtd_ivt_val numeric(32,5),
qtd_ivt_pct numeric(10,2),
qtd_ivt_rank int,
qtd_pdt_vol bigint,
qtd_pdt_val numeric(32,5),
qtd_pdt_pct numeric(10,2),
qtd_pdt_rank int,
qtd_market_algo_cnt numeric(32,5),
qtd_algo_cnt numeric(32,5),
qtd_algo_pct numeric(10,2),
qtd_algo_rank int,
qtd_inet_cnt numeric(32,5),
qtd_inet_pct numeric(10,2),
qtd_inet_rank int,
qtd_dma_cnt numeric(32,5),
qtd_dma_pct numeric(10,2),
qtd_dma_rank int,
qtd_brok_cnt numeric(32,5),
qtd_brok_pct numeric(10,2),
qtd_brok_rank int,
qtd_ord_cnt bigint,
qtd_trd_cnt bigint,
qtd_ot_ratio numeric(10,2),
buy_vol bigint,
buy_val numeric(32,5),
sell_vol bigint,
sell_val numeric(32,5)
);

alter table dibots_v2.broker_rank_qtd add constraint broker_rank_qtd_pkey primary key (trading_date, participant_code);

create index broker_rank_qtd_ext_id_idx on dibots_v2.broker_rank_qtd (external_id);

select * from dibots_v2.broker_rank_qtd order by trading_date

insert into dibots_v2.broker_rank_qtd (trading_date, year, month, qtr, external_id, participant_code, participant_name, qtd_day_count, qtd_total_vol, qtd_total_val, qtd_total_pct, qtd_total_rank, 
qtd_local_vol, qtd_local_val, qtd_local_pct, qtd_local_rank, 
qtd_foreign_vol, qtd_foreign_val, qtd_foreign_pct, qtd_foreign_rank, 
qtd_nominee_total_vol, qtd_nominee_total_val, qtd_nominee_total_pct, qtd_nominee_total_rank, 
qtd_nominee_local_vol, qtd_nominee_local_val, qtd_nominee_local_pct, qtd_nominee_local_rank, 
qtd_nominee_foreign_vol, qtd_nominee_foreign_val, qtd_nominee_foreign_pct, qtd_nominee_foreign_rank, 
qtd_inst_total_vol, qtd_inst_total_val, qtd_inst_total_pct, qtd_inst_total_rank, 
qtd_inst_local_vol, qtd_inst_local_val, qtd_inst_local_pct, qtd_inst_local_rank, 
qtd_inst_foreign_vol, qtd_inst_foreign_val, qtd_inst_foreign_pct, qtd_inst_foreign_rank, 
qtd_retail_total_vol, qtd_retail_total_val, qtd_retail_total_pct, qtd_retail_total_rank, 
qtd_retail_local_vol, qtd_retail_local_val, qtd_retail_local_pct, qtd_retail_local_rank, 
qtd_retail_foreign_vol, qtd_retail_foreign_val, qtd_retail_foreign_pct, qtd_retail_foreign_rank, 
qtd_proprietary_vol, qtd_proprietary_val, qtd_proprietary_pct, qtd_proprietary_rank, 
qtd_ivt_vol, qtd_ivt_val, qtd_ivt_pct, qtd_ivt_rank, 
qtd_pdt_vol, qtd_pdt_val, qtd_pdt_pct, qtd_pdt_rank)
select trading_date, year, month, qtr, external_id, participant_code, participant_name, 1, total_trade_volume, total_trade_value, total_pct, rank_total,
local_trade_volume, local_trade_value, local_pct, rank_local,
foreign_trade_volume, foreign_trade_value, foreign_pct, rank_foreign,
nominee_total_trade_volume, nominee_total_trade_value, nominee_total_pct, rank_nominee_total,
nominee_local_trade_volume, nominee_local_trade_value, nominee_local_pct, rank_nominee_local,
nominee_foreign_trade_volume, nominee_foreign_trade_value, nominee_foreign_pct, rank_nominee_foreign,
inst_total_trade_volume, inst_total_trade_value, inst_total_pct, rank_inst_total,
inst_local_trade_volume, inst_local_trade_value, inst_local_pct, rank_inst_local,
inst_foreign_trade_volume, inst_foreign_trade_value, inst_foreign_pct, rank_inst_foreign,
retail_total_trade_volume, retail_total_trade_value, retail_total_pct, rank_retail_total,
retail_local_trade_volume, retail_local_trade_value, retail_local_pct, rank_retail_local,
retail_foreign_trade_volume, retail_foreign_trade_value, retail_foreign_pct, rank_retail_foreign,
proprietary_trade_volume, proprietary_trade_value, proprietary_pct, rank_proprietary,
ivt_trade_volume, ivt_trade_value, ivt_pct, rank_ivt,
pdt_trade_volume, pdt_trade_value, pdt_pct, rank_pdt
from dibots_v2.broker_rank_day
where trading_date = '2017-05-02'

--====================
--BROKER_RANK_YTD
--====================

drop table dibots_v2.broker_rank_ytd;
create table dibots_v2.broker_rank_ytd (
trading_date date,
year int,
external_id int,
participant_code int,
participant_name varchar(255),
ytd_day_count int,
ytd_total_vol bigint,
ytd_total_val numeric(32,5),
ytd_total_pct numeric(10,2),
ytd_total_rank int,
ytd_local_vol bigint,
ytd_local_val numeric(32,5),
ytd_local_pct numeric(10,2),
ytd_local_rank int,
ytd_foreign_vol bigint,
ytd_foreign_val numeric(32,5),
ytd_foreign_pct numeric(10,2),
ytd_foreign_rank int,
ytd_nominee_total_vol bigint,
ytd_nominee_total_val numeric(32,5),
ytd_nominee_total_pct numeric(10,2),
ytd_nominee_total_rank int,
ytd_nominee_local_vol bigint,
ytd_nominee_local_val numeric(32,5),
ytd_nominee_local_pct numeric(10,2),
ytd_nominee_local_rank int,
ytd_nominee_foreign_vol bigint,
ytd_nominee_foreign_val numeric(32,5),
ytd_nominee_foreign_pct numeric(10,2),
ytd_nominee_foreign_rank int,
ytd_inst_total_vol bigint,
ytd_inst_total_val numeric(32,5),
ytd_inst_total_pct numeric(10,2),
ytd_inst_total_rank int,
ytd_inst_local_vol bigint,
ytd_inst_local_val numeric(32,5),
ytd_inst_local_pct numeric(10,2),
ytd_inst_local_rank int,
ytd_inst_foreign_vol bigint,
ytd_inst_foreign_val numeric(32,5),
ytd_inst_foreign_pct numeric(10,2),
ytd_inst_foreign_rank int,
ytd_retail_total_vol bigint,
ytd_retail_total_val numeric(32,5),
ytd_retail_total_pct numeric(10,2),
ytd_retail_total_rank int,
ytd_retail_local_vol bigint,
ytd_retail_local_val numeric(32,5),
ytd_retail_local_pct numeric(10,2),
ytd_retail_local_rank int,
ytd_retail_foreign_vol bigint,
ytd_retail_foreign_val numeric(32,5),
ytd_retail_foreign_pct numeric(10,2),
ytd_retail_foreign_rank int,
ytd_proprietary_vol bigint,
ytd_proprietary_val numeric(32,5),
ytd_proprietary_pct numeric(10,2),
ytd_proprietary_rank int,
ytd_ivt_vol bigint,
ytd_ivt_val numeric(32,5),
ytd_ivt_pct numeric(10,2),
ytd_ivt_rank int,
ytd_pdt_vol bigint,
ytd_pdt_val numeric(32,5),
ytd_pdt_pct numeric(10,2),
ytd_pdt_rank int,
ytd_market_algo_cnt numeric(32,5),
ytd_algo_cnt numeric(32,5),
ytd_algo_pct numeric(10,2),
ytd_algo_rank int,
ytd_inet_cnt numeric(32,5),
ytd_inet_pct numeric(10,2),
ytd_inet_rank int,
ytd_dma_cnt numeric(32,5),
ytd_dma_pct numeric(10,2),
ytd_dma_rank int,
ytd_brok_cnt numeric(32,5),
ytd_brok_pct numeric(10,2),
ytd_brok_rank int,
ytd_ord_cnt bigint,
ytd_trd_cnt bigint,
ytd_ot_ratio numeric(10,2),
buy_vol bigint,
buy_val numeric(32,5),
sell_vol bigint,
sell_val numeric(32,5)
);

alter table dibots_v2.broker_rank_ytd add constraint broker_rank_ytd_pkey primary key (trading_date, participant_code);

create index broker_rank_ytd_ext_id_idx on dibots_v2.broker_rank_ytd (external_id);

select * from dibots_v2.broker_rank_ytd order by trading_date desc

insert into dibots_v2.broker_rank_ytd (trading_date, year, external_id, participant_code, participant_name, ytd_day_count, ytd_total_vol, ytd_total_val, ytd_total_pct, ytd_total_rank, 
ytd_local_vol, ytd_local_val, ytd_local_pct, ytd_local_rank, 
ytd_foreign_vol, ytd_foreign_val, ytd_foreign_pct, ytd_foreign_rank, 
ytd_nominee_total_vol, ytd_nominee_total_val, ytd_nominee_total_pct, ytd_nominee_total_rank, 
ytd_nominee_local_vol, ytd_nominee_local_val, ytd_nominee_local_pct, ytd_nominee_local_rank, 
ytd_nominee_foreign_vol, ytd_nominee_foreign_val, ytd_nominee_foreign_pct, ytd_nominee_foreign_rank, 
ytd_inst_total_vol, ytd_inst_total_val, ytd_inst_total_pct, ytd_inst_total_rank, 
ytd_inst_local_vol, ytd_inst_local_val, ytd_inst_local_pct, ytd_inst_local_rank, 
ytd_inst_foreign_vol, ytd_inst_foreign_val, ytd_inst_foreign_pct, ytd_inst_foreign_rank, 
ytd_retail_total_vol, ytd_retail_total_val, ytd_retail_total_pct, ytd_retail_total_rank, 
ytd_retail_local_vol, ytd_retail_local_val, ytd_retail_local_pct, ytd_retail_local_rank, 
ytd_retail_foreign_vol, ytd_retail_foreign_val, ytd_retail_foreign_pct, ytd_retail_foreign_rank, 
ytd_proprietary_vol, ytd_proprietary_val, ytd_proprietary_pct, ytd_proprietary_rank, 
ytd_ivt_vol, ytd_ivt_val, ytd_ivt_pct, ytd_ivt_rank, 
ytd_pdt_vol, ytd_pdt_val, ytd_pdt_pct, ytd_pdt_rank)
select trading_date, year, external_id, participant_code, participant_name, 1, total_trade_volume, total_trade_value, total_pct, rank_total,
local_trade_volume, local_trade_value, local_pct, rank_local,
foreign_trade_volume, foreign_trade_value, foreign_pct, rank_foreign,
nominee_total_trade_volume, nominee_total_trade_value, nominee_total_pct, rank_nominee_total,
nominee_local_trade_volume, nominee_local_trade_value, nominee_local_pct, rank_nominee_local,
nominee_foreign_trade_volume, nominee_foreign_trade_value, nominee_foreign_pct, rank_nominee_foreign,
inst_total_trade_volume, inst_total_trade_value, inst_total_pct, rank_inst_total,
inst_local_trade_volume, inst_local_trade_value, inst_local_pct, rank_inst_local,
inst_foreign_trade_volume, inst_foreign_trade_value, inst_foreign_pct, rank_inst_foreign,
retail_total_trade_volume, retail_total_trade_value, retail_total_pct, rank_retail_total,
retail_local_trade_volume, retail_local_trade_value, retail_local_pct, rank_retail_local,
retail_foreign_trade_volume, retail_foreign_trade_value, retail_foreign_pct, rank_retail_foreign,
proprietary_trade_volume, proprietary_trade_value, proprietary_pct, rank_proprietary,
ivt_trade_volume, ivt_trade_value, ivt_pct, rank_ivt,
pdt_trade_volume, pdt_trade_value, pdt_pct, rank_pdt
from dibots_v2.broker_rank_day
where trading_date = '2017-05-02'