--===================
-- FBM100 directors
--===================

select c.stock_code, c.dbt_entity_id, c.external_id, c.company_name, d.person_id, d.role_type, d.role_desc, d.is_board_member, d.is_officer, d.year_joint_company, d.year_appointed_to_board
from
(select a.stock_code, b.stock_identifier as dbt_entity_id, b.stock_identifier_ex as external_id, b.company_name from dibots_v2.exchange_daily_transaction a
left join dibots_v2.exchange_stock_profile b
on a.stock_code = b.stock_code
where a.transaction_date = '2021-06-30' and a.fbm100_flag = true and b.eff_end_date is null and b.delisted_date is null) c
left join 
dibots_v2.company_person_role d
on c.dbt_entity_id = d.company_id 
where (d.eff_end_date >= '2021-06-30' or d.eff_end_date is null) and d.eff_from_date <= '2021-06-30' and d.deleted = false;

create table staging.fbm100_directors (
id int generated by default as identity primary key,
stock_code varchar(10),
company_id uuid,
comp_ext_id bigint,
company_name varchar(100),
person_id uuid,
person_ext_id bigint,
person_name varchar(200),
role_type varchar(10),
role_desc varchar(100),
is_board_member bool,
is_officer bool,
year_joint_company int,
year_appointed_to_board int
);

select * from dibots_v2.company_person_role limit 10

select * from dibots_v2.exchange_stock_profile limit 10


--====================
-- ESG
--====================

select a.stock_code, b.stock_identifier as dbt_entity_id, b.stock_identifier_ex as external_id, b.company_name from dibots_v2.exchange_daily_transaction a
left join dibots_v2.exchange_stock_profile b
on a.stock_code = b.stock_code
where a.transaction_date = '2021-06-30' and a.fbm100_flag = true and b.eff_end_date is null and b.delisted_date is null


select wvb_esg_id, company_id, fiscal_period_end_date, row_number() over (partition by company_id order by fiscal_period_end_date desc)  from dibots_v2.esg_hdr where company_id in (
select b.stock_identifier as dbt_entity_id from dibots_v2.exchange_daily_transaction a
left join dibots_v2.exchange_stock_profile b
on a.stock_code = b.stock_code
where a.transaction_date = '2021-06-30' and a.fbm100_flag = true and b.eff_end_date is null and b.delisted_date is null) and
fiscal_period_end_date <= '2021-06-30'

drop table if exists staging.fbm100_esg_hdr;
create table staging.fbm100_esg_hdr (
dbt_entity_id uuid,
external_id bigint,
stock_code varchar(10),
company_name varchar(100),
wvb_esg_id bigint,
fiscal_period_end_date timestamptz
);

select * from staging.fbm100_esg_hdr

select dbt_entity_id, count(*) from staging.fbm100_esg_hdr group by dbt_entity_id having count(*) < 3

insert into staging.fbm100_esg_hdr (dbt_entity_id, wvb_esg_id, fiscal_period_end_date)
select company_id, wvb_esg_id, fiscal_period_end_date from (
select wvb_esg_id, company_id, fiscal_period_end_date, fiscal_period_end_month, periodicity, row_number() over (partition by company_id order by fiscal_period_end_date desc)  
from dibots_v2.esg_hdr where company_id in (
select b.stock_identifier as dbt_entity_id from dibots_v2.exchange_daily_transaction a
left join dibots_v2.exchange_stock_profile b
on a.stock_code = b.stock_code
where a.transaction_date = '2021-06-30' and a.fbm100_flag = true and b.eff_end_date is null and b.delisted_date is null)
) c
where c.row_number <= 3
order by company_id, fiscal_period_end_date

update staging.fbm100_esg_hdr c
set
external_id = d.external_id,
stock_code = d.stock_code,
company_name = d.company_name
FROM 
(select a.stock_code, b.stock_identifier as dbt_entity_id, b.stock_identifier_ex as external_id, b.company_name from dibots_v2.exchange_daily_transaction a
left join dibots_v2.exchange_stock_profile b
on a.stock_code = b.stock_code
where a.transaction_date = '2021-06-30' and a.fbm100_flag = true and b.eff_end_date is null and b.delisted_date is null) d
where c.dbt_entity_id = d.dbt_entity_id

--=============================

--drop table staging.fbm100_esg_val;
create table staging.fbm100_esg_val (
id bigint generated by default as identity,
wvb_esg_id bigint,
data_item_id bigint,
data_item_desc text,
numeric_value numeric(25,6)
);

select * from staging.fbm100_esg_val order by wvb_esg_id, data_item_id;

--insert into staging.fbm100_esg_val (wvb_esg_id, data_item_id, numeric_value)
select a.wvb_esg_id, b.wvb_data_item_id, b.numeric_value from staging.fbm100_esg_hdr a, dibots_v2.esg_value b
where a.wvb_esg_id = b.wvb_esg_id

--update staging.fbm100_esg_val a
set
data_item_desc = b.item_desc
from dibots_v2.ref_data_item b
where a.data_item_id = b.data_item_perm_id;


-- final result for ESG
-- 1. Board composition, 
--		15001 total director
--		15002 outside member of boards
--		15003 total auditors
--		15004 outside auditors
--		15005 members of compensation comittee
--		19744 Non-Independent Executive Director (MD/CEO)
--		19745 Non-Independent Non-Executive Directors (including Chairman)
--		19746 Independent Non-Executive Directors
--		19747 Nominating Committee (Total)
--		19748 Members of Board Risk Committee (Total)
--		19749 Members of Corporate Governance Committee
--19832	Members of Board Halal/Shariah Committee (Total)
-- 2. Shareholders and AGM attended
--		15006 num board meetings
--		15007 num of investor meetings
--		15009 Study Sessions For Media - Esg
--		19750 num audit meetings
--		19750 Number of Audit Meetings
--		19751 Number of Remuneration Meetings
--		19752 Number of Nominating Meetings
--		19753 Number of Corporate Governance Meetings
--		19754 Number of Board Risk Committee
--		19755 Number of Institutional Investors Engagement Sessions
--		19756 Local investor conference/roadshows (number of times)
--		19757 Foreign investors conference/roadshows (number of times)
--		19758 Shareholders and proxies attended AGM (headcount)
-- 3. Shareholders
--		15011 num of shareholders
--		15012 outstanding shares ('000)
--		19759 Number of shareholders - Local
--		19760 Number of shareholders - Foreign
--		19761 Number of shareholders - Individuals
--		19762 Number of shareholders - Institutions
--		19763 Number of shareholders - Government/Agencies
--		19764 Number of shareholders - Nominees
--		19765 Number of shareholders - Corporate body
-- 4. Ratio
--		15014 foreign shares (%)
--15015	Ratio Of Shares Held By Individual/Other Shareholders (Ye) % - Esg
--		15016 Ratio Of Shares Held By Institutions (Ye) % - Esg
--		15017 Ratio Of Shares Held By Government/Agencies (Ye) % - Esg
--		19766 Ratio of shares held by local investors %
--		19767 Ratio of shares held by nominees %
--		19768 Ratio of shares held by corporate body %
-- 5. Employee Age Group
--		15022 Full-Time Employees - Esg
--		15023 Apprentices/Trainees - Esg
--		15024 Contractors - Esg
--		15029 Ratio Of Female/Male Employees % - Esg
--		15032 Employees Who Took Childcare Leave - Esg
--		15036 Employees Who Used The Program For Returning To Work After Taking Childcare Leave - Esg
--		15038 Women in management (%)
--19769	Permanent Full Time #
--19770	Contract Full Time #
--19771	Part-time Employees #
--19773	Female Employees #
--19774	Male Employees #
--19775	Local Employees #
--19776	Foreign Employees #
--19777	Employees With disabilities #
--19779	Total Employees #
--19780	Average Employees #
--19781	White-collar/ Technical workers %
--19782	Blue-collar/ Non-Technical workers %
--19783	Full-Time Employees %
--19784	Part-Time Employees %
--19785	Female Employees %
--19786	Male Employees %
--19787	Women in Board Composition %
--19788	Local Employees %
--19789	Foreign Employees %
--19790	Below 35 years %
--19791	Above 35 years %
--19792	30 to 50 years %
--19793	Above 50 years %
--19794	Below 30 years #
--19795	Above 35 years #
--19796	30 to 50 years #
--19797	Above 50 years #
--19798	Baby Boomers (1965 and before) #
--19799	Gen X (1966 - 1985) #
--19800	Millenials (1986 - 1995) #
--19801	Post Millenials (Born after 1995 ) #
-- 6. Employee average service years
--		15026 Average Service Years - Esg

-- 7. Employee training
--		15027 avg hours if training per employee
--		15041 safety-fatalities (#)
--		15042 safety-lost workday injuries (#)
--		15043 Safety - Commuting Accidents # - Esg
--		15044 Safety - # Of Safety Training Sessions - Esg
--		15047 safety-total recordable case frequency rate
--		15048 safety-lost time injury frequency ration
--19802	Number of employee attend training (Total)
--19803	Number of employee attend training (Male)
--19804	Number of employee attend training (Female)
--19805	Total hours of staff training (Total)
--19806	Total hours of staff training (Male)
--19807	Total hours of staff training (Female)
--19808	Total period training per employee (hours)
--19809	Total mandays training per employee (days)
--19810	Training investment per employee (Value LC'000)
--19811	Staff Costs (Value LC'000)
--19812	Employee turnover (%)
--19813	Number of New Hires
--19814	Number of Volunteers
--19815	Total Employee Volunteering Hours
--19817	Safety – Accidents
--19818	Safety – Accident Frequency Rate (AFR)
--19819	Safety – Accident Severity Rate (ASR)
--		19820 safety-fatal accident rate
--		19821 safety-workplace injury #
--		19823 safety-occupational diseases #
--		19824 safety-occupational diseases rate
--19834	Shariah Trainning Programme (Yes_1, No_blank)
-- 8. Gas Emission
--		15050 Electricity 10 Mwh Annual Energy Consumption  - Esg
--		15053 Gasoline (Kl) Annual Energy Consumption  - Esg
--		15054 Fuel (Kl) Annual Energy Consumption - Esg
--		15056 Lng (Tons) Annual Energy Consumption  - Esg
--		15057 Lpg (Tons) Annual Energy Consumption  - Esg
--		15058 Total Energy Consumption - Esg
--		15059 Co2 Emissions (Ton) Annual  - Esg
--		15060 General Annual Waste Generation T - Esg
--		15061 Disposal Annual Waste Generation T - Esg
--		15062 Volume Of Landfilled Waste Annual Waste Generation  - Esg
--		15063 Recycled Annual Waste Generation - Esg
--		15064 Recycled Ratio (%) - Esg
--		15065 Disposal Ratio (%) - Esg
--		15066 total water consumption (m3)
--		15070 total waste water (m3)
--19836	Direct Electricity consumption (megawatt-hour)(Mwh)
--19837	Indirect Electricity consumption (megawatt-hour)(Mwh)
--19838	Total Direct Energy Consumption (metric ton)
--19839	Total Indirect Energy Consumption (metric ton)
--19840	Methane Emissions (metric ton)
--19841	Nitrous Oxide Emissions  (metric ton)
--19842	Sulphur Oxide Emissions  (metric ton)
--19845	Other Greenhouse Gasses (GHG) Emissions (million tCO2e)
--19846	Total Greenhouse Gases (GHG) Emissions (metric ton)
--19847	Total Greenhouse Gases (GHG) Emissions (million tCO2e)
--19848	Other Direct Gas Emissions (metric ton)
--19849	Other Indirect Gas Emissions (metric ton)
--19851	Hazardous wastes (metric ton)
--19852	Non-hazardous wastes (metric ton)
--19853	Volatile Organic Compounds (VOC) (metric ton)
--19854	Total Discharges to Water (metric ton)
--19855	Fresh Water withdrawal (cubic meter)(m3)
--19856	Solar Energy Production
-- 9. Expenditure on Annual Environment Protection
--		15040 Donations (Value Lc'000) - Esg
--		15075 Expenditure On Annual Environmental Protection - Esg
--19816	Community Investment

select a.dbt_entity_id, a.external_id, a.stock_code, a.company_name, a.fiscal_period_end_date, b.data_item_id, b.data_item_desc, b.numeric_value 
from staging.fbm100_esg_hdr a, staging.fbm100_esg_val b
where a.wvb_esg_id = b.wvb_esg_id
order by a.dbt_entity_id, a.fiscal_period_end_date, b.data_item_id


-- to get every data item desc
select * from (
select distinct data_item_id from staging.fbm100_esg_val order by data_item_id) a, dibots_v2.ref_data_item b
where a.data_item_id = b.data_item_perm_id

--==========================
-- final table
--=================

--drop table staging.fbm100_esg;
create table staging.fbm100_esg (
id bigint generated by default as identity,
dbt_entity_id uuid,
external_id bigint,
stock_code varchar(10),
company_name text,
fiscal_period_end_date timestamptz,
employee_age_30_to50 numeric(25,3),
employee_age_30_to_50_pct numeric(25,3),
employee_above_35 numeric(25,3),
employee_above_35_pct numeric(25,3),
employee_above_50 numeric(25,3),
employee_above_50_pct numeric(25,3),
no_of_trainees numeric(25,3),
employee_avg numeric(25,3),
training_avg_hour_per_employee numeric(25,3),
avg_service_years numeric(25,3),
baby_boomer_before_1965 numeric(25,3),
employee_below_30 numeric(25,3),
employee_below_35_pct numeric(25,3),
non_tech_worker_pct numeric(25,3),
co2_emission_ton numeric(25,3),
community_investment numeric(25,3),
contract_full_time numeric(25,3),
contractor numeric(25,3),
direct_electricity_consumption_mwh numeric(25,3),
annual_waste_generation_ton numeric(25,3),
disposal_ratio_pct numeric(25,3),
Donation_000 numeric(25,3),
annual_energy_consumption_10mwh numeric(25,3),
employee_turnover_pct numeric(25,3),
employee_childcare_leave numeric(25,3),
employee_return_to_work_program_after_childcare_leave numeric(25,3),
employees_with_disabilities numeric(25,3),
annual_expenditure_on_environmental_protection numeric(25,3),
no_of_female_employee numeric(25,3),
female_employee_pct numeric(25,3),
no_of_foreign_employee numeric(25,3),
foreign_employee_pct numeric(25,3),
no_of_foreign_investors_conference numeric(25,3),
fresh_water_withdrawal_m3 numeric(25,3),
annual_energy_consumption_fuel_kl numeric(25,3),
no_of_full_time_employee numeric(25,3),
full_time_employee_pct numeric(25,3),
annual_energy_consumption_gasoline_kl numeric(25,3),
Genx_1966_1985 numeric(25,3),
annual_general_waster_generation_ton numeric(25,3),
hazardous_waster_metric_ton numeric(25,3),
independent_non_executive_dir numeric(25,3),
indirect_energy_consumption_mwh numeric(25,3),
annual_energy_consumption_lng_ton numeric(25,3),
no_of_local_employee numeric(25,3),
local_employee_pct numeric(25,3),
local_investor_conference numeric(25,3),
annual_energy_consumption_lpg_ton numeric(25,3),
no_of_male_employee numeric(25,3),
male_employee_pct numeric(25,3),
members_of_boards_shariah_committee numeric(25,3),
members_of_boards_of_auditors numeric(25,3),
member_of_boards_of_directors numeric(25,3),
members_of_board_risk_committee numeric(25,3),
members_of_compensation_committee numeric(25,3),
members_of_corporate_governance_committee numeric(25,3),
methane_emission_metric_ton numeric(25,3),
Milennials_1986_1995 numeric(25,3),
nitrous_oxide_emission_metric_ton numeric(25,3),
nominating_committee numeric(25,3),
non_hazardous_waste_metric_ton numeric(25,3),
non_independent_executive_director numeric(25,3),
non_independent_non_executive_directors_inc_chairman numeric(25,3),
no_of_audit_meetings numeric(25,3),
no_of_board_meetings numeric(25,3),
no_of_board_risk_committee numeric(25,3),
no_of_corp_gov_meeting numeric(25,3),
no_of_female_employee_training numeric(25,3),
no_of_male_employee_training numeric(25,3),
no_of_total_employee_training numeric(25,3),
no_of_shariah_committee_meeting numeric(25,3),
no_of_inst_investor_engagement_session numeric(25,3),
no_of_investor_meetings numeric(25,3),
no_of_new_hires numeric(25,3),
no_of_nominating_meetings numeric(25,3),
no_of_remuneration_meetings numeric(25,3),
no_of_corp_body_shareholder numeric(25,3),
no_of_shareholder numeric(25,3),
no_of_foreign_shareholder numeric(25,3),
no_of_gov_agency_shareholder numeric(25,3),
no_of_individual_shareholder numeric(25,3),
no_of_inst_shareholder numeric(25,3),
no_of_local_shareholder numeric(25,3),
no_of_nominee_shareholder numeric(25,3),
no_of_volunteers numeric(25,3),
other_direct_gas_emission_metric_ton numeric(25,3),
other_greenhouse_gas_emissions_million_tco2e numeric(25,3),
other_indirect_gas_emissions_metric_ton numeric(25,3),
outside_member_of_board_of_auditors numeric(25,3),
outside_member_of_board_of_director numeric(25,3),
outstanding_share_000 numeric(25,3),
no_of_part_time_employee numeric(25,3),
part_time_employee_pct numeric(25,3),
no_of_permanent_full_time numeric(25,3),
post_millennials_after_1995 numeric(25,3),
halal_certified_product_pct numeric(25,3),
products_with_halal_cert numeric(25,3),
female_male_employee_ratio_pct numeric(25,3),
corp_body_held_share_pct numeric(25,3),
foreign_investor_held_share_pct numeric(25,3),
gov_agencies_held_share_pct numeric(25,3),
individual_held_share_pct numeric(25,3),
inst_held_share_pct numeric(25,3),
local_held_share_pct numeric(25,3),
nominees_held_share_pct numeric(25,3),
recycled_annual_waste_generation numeric(25,3),
recycled_ratio_pct numeric(25,3),
no_of_safety_training numeric(25,3),
no_of_commuting_accident numeric(25,3),
fatal_accident_rate numeric(25,3),
no_of_fatalities numeric(25,3),
lost_time_injury_ratio numeric(25,3),
no_of_lost_workday_injury numeric(25,3),
no_occupational_diseases numeric(25,3),
occupational_diseases_rate numeric(25,3),
total_recordable_case_frequency_rate numeric(25,3),
accident_frequency_rate numeric(25,3),
accident_severity_rate numeric(25,3),
accidents numeric(25,3),
workplace_injury numeric(25,3),
workplace_injury_rate numeric(25,3),
agm_headcount numeric(25,3),
shariah_compliant_service_pct numeric(25,3),
shariah_training_programme numeric(25,3),
solar_energy_production numeric(25,3),
staff_cost_lc000 numeric(25,3),
study_session_for_media numeric(25,3),
sulphur_oxide_emissions_metric_ton numeric(25,3),
total_direct_energy_consumption_metric_ton numeric(25,3),
total_discharges_to_water_metric_ton numeric(25,3),
total_employee_volunteer_hour numeric(25,3),
total_employee numeric(25,3),
total_energy_consumption numeric(25,3),
total_greenhouse_gas_emissions_metric_ton numeric(25,3),
total_greenhouse_gas_emission_million_tCO2e numeric(25,3),
total_hours_training_female numeric(25,3),
total_hours_training_male numeric(25,3),
total_hours_of_training numeric(25,3),
total_indirect_energy_consumption_metric_ton numeric(25,3),
total_manday_training_per_employee numeric(25,3),
total_period_training_per_employee_hour numeric(25,3),
total_waste_water_m3 numeric(25,3),
total_water_consumption_m3 numeric(25,3),
total_investment_per_employee_lc000 numeric(25,3),
volative_organic_compound_metric_ton numeric(25,3),
annual_volume_of_landfilled_waste_generation numeric(25,3),
tech_workers_pct numeric(25,3),
women_in_board_pct numeric(25,3),
women_in_management_pct numeric(25,3)
);

select * from staging.fbm100_esg

update staging.fbm100_esg a
set
stock_code = b.stock_code
from dibots_v2.exchange_stock_profile b
where a.dbt_entity_id = b.stock_identifier and b.eff_end_date is null;

-- arrange the columns in the right way

select dbt_entity_id, external_id, stock_code, company_name, fiscal_period_end_date,
member_of_boards_of_directors, outside_member_of_board_of_director, members_of_boards_of_auditors, outside_member_of_board_of_auditors, members_of_compensation_committee, non_independent_executive_director,
non_independent_non_executive_directors_inc_chairman,independent_non_executive_dir, nominating_committee, no_of_board_risk_committee, members_of_corporate_governance_committee, members_of_boards_shariah_committee,
women_in_board_pct, women_in_management_pct,
no_of_board_meetings, no_of_investor_meetings, no_of_audit_meetings, no_of_remuneration_meetings, no_of_nominating_meetings, no_of_corp_gov_meeting, members_of_board_risk_committee,
no_of_inst_investor_engagement_session, local_investor_conference, no_of_foreign_investors_conference, no_of_shariah_committee_meeting, agm_headcount, 
outstanding_share_000, no_of_shareholder, no_of_local_shareholder, no_of_foreign_shareholder, no_of_individual_shareholder, no_of_inst_shareholder, no_of_gov_agency_shareholder, no_of_nominee_shareholder,
no_of_corp_body_shareholder, foreign_investor_held_share_pct, individual_held_share_pct, gov_agencies_held_share_pct, local_held_share_pct, nominees_held_share_pct, corp_body_held_share_pct, inst_held_share_pct,
total_employee, no_of_full_time_employee, full_time_employee_pct, no_of_part_time_employee, part_time_employee_pct,no_of_permanent_full_time, no_of_trainees, contractor, 
contract_full_time, no_of_female_employee, female_employee_pct, no_of_male_employee, male_employee_pct,employee_below_30, employee_below_35_pct, employee_age_30_to50, 
employee_age_30_to_50_pct, employee_above_35, employee_above_35_pct, employee_above_50, employee_above_50_pct,baby_boomer_before_1965, post_millennials_after_1995, Genx_1966_1985, Milennials_1986_1995,
employee_avg, no_of_new_hires, no_of_volunteers, 
non_tech_worker_pct, tech_workers_pct, employees_with_disabilities, no_of_local_employee, local_employee_pct, no_of_foreign_employee, foreign_employee_pct, female_male_employee_ratio_pct, 
avg_service_years, training_avg_hour_per_employee, no_of_female_employee_training, no_of_male_employee_training, no_of_total_employee_training, total_hours_training_female, total_hours_training_male,
total_hours_of_training, total_manday_training_per_employee, total_period_training_per_employee_hour, shariah_training_programme, 
no_of_commuting_accident, fatal_accident_rate, no_of_fatalities, lost_time_injury_ratio, no_of_lost_workday_injury, no_occupational_diseases, occupational_diseases_rate, total_recordable_case_frequency_rate, 
accident_frequency_rate, accident_severity_rate, accidents, workplace_injury, workplace_injury_rate, total_employee_volunteer_hour,
no_of_safety_training, employee_turnover_pct, employee_childcare_leave, employee_return_to_work_program_after_childcare_leave, co2_emission_ton, methane_emission_metric_ton, nitrous_oxide_emission_metric_ton,
sulphur_oxide_emissions_metric_ton, total_greenhouse_gas_emissions_metric_ton, total_greenhouse_gas_emission_million_tCO2e, other_direct_gas_emission_metric_ton, other_greenhouse_gas_emissions_million_tco2e,
other_indirect_gas_emissions_metric_ton, volative_organic_compound_metric_ton,direct_electricity_consumption_mwh, annual_energy_consumption_10mwh, annual_energy_consumption_fuel_kl, annual_energy_consumption_gasoline_kl,
annual_energy_consumption_lng_ton, annual_energy_consumption_lpg_ton, total_direct_energy_consumption_metric_ton, total_indirect_energy_consumption_metric_ton, total_energy_consumption, indirect_energy_consumption_mwh,
total_water_consumption_m3, total_waste_water_m3, total_discharges_to_water_metric_ton, fresh_water_withdrawal_m3,  annual_general_waster_generation_ton, hazardous_waster_metric_ton, recycled_annual_waste_generation,
recycled_ratio_pct, solar_energy_production, annual_volume_of_landfilled_waste_generation, annual_waste_generation_ton, disposal_ratio_pct, non_hazardous_waste_metric_ton, 
annual_expenditure_on_environmental_protection, Donation_000, community_investment, total_investment_per_employee_lc000, staff_cost_lc000
from staging.fbm100_esg
order by stock_code, fiscal_period_end_date