
select * from dibots_rod.rod_method_mapping

select * from dibots_rod.rod_excel_storage

select * from dibots_rod.rod_registry_of_depository_record

select * from dibots_rod.company_stock--where stock_code like '8869%'

--delete from dibots_rod.rod_registry_of_depository_record where data_source in (4,5);
--DELETE FROM dibots_rod.rod_excel_storage where id in (4,5);

select * from dibots_rod.broker_profile

select * from dibots_rod.rod_registry_of_depository_record

select count(*) from dibots_rod.rod_registry_of_depository_record where person_dbt_id is not null

select mem_no, investor_id, person_name, person_mk, shareholder, person_dbt_id, person_ext_id from dibots_rod.rod_registry_of_depository_record where person_dbt_id is not null

-- checking the comp dbt id matched
select a.comp_dbt_id, a.person_name, a.qualifier, a.shareholder, a.group_type, b.display_name from dibots_rod.rod_registry_of_depository_record a, dibots_v2.company_profile b
where a.comp_dbt_id = b.dbt_entity_id

select * from dibots_rod.rod_registry_of_depository_record where entity_type = 'COMPANY' and group_type <> 'NOMINEES'

select * from dibots_rod.rod_registry_of_depository_record where lower(shareholder) like 'etiqa%'

select * from dibots_v2.entity_identifier where identifier = '258939-H'

select * from dibots_v2.company_profile where dbt_entity_id = '3327730f-15ab-47ad-9ae0-896cd76e8de7'

select count(*) from dibots_v2.entity_identifier a, dibots_v2.company_profile b 
where a.dbt_entity_id = b.dbt_entity_id and b.country_of_incorporation = 'MYS' and b.active = true and a.identifier_type = 'REGIST'

-- roc matching
select a.roc_no, b.identifier, b.dbt_entity_id from dibots_rod.rod_registry_of_depository_record a, dibots_v2.entity_identifier b
where a.roc_no = regexp_replace(b.identifier, '-', '', 'g') and b.eff_end_date is null and b.deleted = false and a.comp_dbt_id is null and a.entity_type = 'COMPANY'

-- comp name matching
select a.id, a.shareholder, b.display_name, b.dbt_entity_id, b.external_id from dibots_rod.rod_registry_of_depository_record a, dibots_rod.company_profile b
where lower(a.shareholder) = regexp_replace(lower(b.display_name), '\.', '', 'g') and a.entity_type = 'COMPANY' and b.country_of_incorporation = 'MYS'

select * from dibots_v2.company_profile where regexp_replace(lower(display_name), '\.', '', 'g') = 'ai capital sdn bhd'--'ybg yap consolidated sdn bhd'

select display_name, regexp_replace(lower(display_name), '\.', '', 'g') from dibots_v2.company_profile where dbt_entity_id = 'fa447446-d4d4-4559-b866-6b03d05b1839'

select * from dibots_rod.rod_registry_of_depository_record where comp_dbt_id is not null

select * from dibots_rod.rod_registry_of_depository_record where person_mk is not null


select * from dibots_v2.entity_identifier where identifier_type = 'REGIST' and regexp_replace(identifier, '-', '', 'g') = '42234H' and deleted = false and eff_end_date is null


create table dibots_rod.rod_method_mapping (
id int generated by default as identity primary key,
comp_dbt_id uuid,
comp_ext_id bigint,
stock_code text,
stock_name text,
method int,
method_desc text,
created_dtime timestamptz not null,
created_by varchar(100) not null,
modified_dtime timestamptz,
modified_by varchar(100),
constraint rod_method_uniq unique (stock_code)
);

select * from dibots_rod.rod_method_mapping

select stock_identifier, stock_identifier_ex, stock_code, short_name from dibots_rod.active_stock_view where stock_code = '1015'

--insert into dibots_rod.rod_method_mapping (comp_dbt_id, comp_ext_id, stock_code, stock_name, method, method_desc, created_dtime, created_by)
values ('b178a011-0645-4bb0-80bc-eaa540ffde0f', 6204, '1015', 'AMBANK', 6, 'no header, date in sheet name', now(), 'kangwei')

values('9b9bfbd8-ef7a-4d6a-9871-36b30e0040f8', 10708, '6068', 'PCCS', 5, 'has header but only 9 columns', now(), 'kangwei')

values ('d50681cb-573e-4a38-8ab9-13907b63a164', 31797, '0038', 'ARTRONIQ', 4, '3 row header 8 columns', now(), 'kangwei');

values ('998c4edf-2d43-46f9-a130-55d0c147beba', 4197700, '0219', 'RL', 3, 'no header, 16 columns', now(), 'kangwei')

values ('c6779cfc-8bcb-42d4-ab46-b23d3803a888', 25658, '7081', 'PHARMA', 2, 'has header, but only 16 columns', now(), 'kangwei');

values ('1468392c-0e27-44b2-98cc-c4415d6f5ed9', 34865, '0056', 'NCT', 1, 'nct method', now(), 'kangwei')



-- CAUTION!
truncate table dibots_rod.rod_excel_storage, dibots_rod.rod_registry_of_depository_record restart identity

vacuum (analyze) dibots_rod.rod_excel_storage;
vacuum (analyze) dibots_rod.rod_registry_of_depository_record;