drop table if exists customer_info;
create table customer_info (
cust_id int generated by default as identity primary key,
cust_text varchar(20)
);

insert into customer_info (cust_text) values ('asdfadsf')

select count(*) from customer_info

drop table if exists customer_txn;
create table customer_txn (
txn_id int generated by default as identity primary key,
cust_id int not null,
txn_amt int
);

select count(*) from customer_txn

create index cust_id_idx on customer_txn(cust_id);

explain analyze
select a.cust_id, count(b.txn_id), sum(b.txn_amt) as total_txn from customer_info a, customer_txn b
where a.cust_id = b.cust_id
group by a.cust_id order by sum(b.txn_amt) desc

explain analyze

select a.cust_id, count(b.txn_id), sum(b.txn_amt) as total_txn
from customer_info a inner join customer_txn b on a.cust_id = b.cust_id
group by a.cust_id order by sum(b.txn_amt) desc

explain analyze

select a.cust_id, b.txn_count, b.total_txn from customer_info a
inner join (select c.cust_id, count(c.txn_id) as txn_count, sum(c.txn_amt) as total_txn from customer_txn c group by c.cust_id) b
on a.cust_id = b.cust_id
order by b.total_txn desc

