--====================================
-- STOCKS that gain, loss, no change
--====================================

CREATE TABLE dibots_v2.bursa_equities_history (
	id int8 generated by default as identity,
	"no" int8 NULL,
	name varchar NULL,
	code varchar NULL,
	rem varchar NULL,
	last_done numeric NULL,
	lacp numeric NULL,
	chg numeric NULL DEFAULT 0,
	pct_chg numeric NULL DEFAULT 0,
	vol_00 numeric(25, 3) NULL DEFAULT 0,
	buy_vol_00 numeric(25, 3) NULL,
	buy numeric NULL,
	sell numeric NULL,
	sell_vol_00 numeric(25, 3) NULL,
	high numeric NULL DEFAULT 0,
	low numeric NULL DEFAULT 0,
	"date" timestamp NOT NULL,
	logid varchar NULL,
	CONSTRAINT bursa_eq_hist_pkey primary key (date, code)
) PARTITION BY RANGE (date);

CREATE INDEX bursa_eq_hist_date_idx ON dibots_v2.bursa_equities_history USING btree (date);

create table dibots_v2.bursa_equities_history_2021q1 partition of dibots_v2.bursa_equities_history 
for values from ('2021-01-01') to ('2021-04-01');
create table dibots_v2.bursa_equities_history_2021q2 partition of dibots_v2.bursa_equities_history 
for values from ('2021-04-01') to ('2021-07-01');
create table dibots_v2.bursa_equities_history_2021q3 partition of dibots_v2.bursa_equities_history 
for values from ('2021-07-01') to ('2021-10-01');
create table dibots_v2.bursa_equities_history_2021q4 partition of dibots_v2.bursa_equities_history 
for values from ('2021-10-01') to ('2022-01-01');
create table dibots_v2.bursa_equities_history_2022q1 partition of dibots_v2.bursa_equities_history 
for values from ('2022-01-01') to ('2022-04-01');
create table dibots_v2.bursa_equities_history_2022q2 partition of dibots_v2.bursa_equities_history 
for values from ('2022-04-01') to ('2022-07-01');
create table dibots_v2.bursa_equities_history_2022q3 partition of dibots_v2.bursa_equities_history 
for values from ('2022-07-01') to ('2022-10-01');
create table dibots_v2.bursa_equities_history_2022q4 partition of dibots_v2.bursa_equities_history 
for values from ('2022-10-01') to ('2023-01-01');
create table dibots_v2.bursa_equities_history_2023q1 partition of dibots_v2.bursa_equities_history 
for values from ('2023-01-01') to ('2023-04-01');
create table dibots_v2.bursa_equities_history_2023q2 partition of dibots_v2.bursa_equities_history 
for values from ('2023-04-01') to ('2023-07-01');
create table dibots_v2.bursa_equities_history_2023q3 partition of dibots_v2.bursa_equities_history 
for values from ('2023-07-01') to ('2023-10-01');
create table dibots_v2.bursa_equities_history_2023q4 partition of dibots_v2.bursa_equities_history 
for values from ('2023-10-01') to ('2024-01-01');
create table dibots_v2.bursa_equities_history_2024q1 partition of dibots_v2.bursa_equities_history 
for values from ('2024-01-01') to ('2024-04-01');
create table dibots_v2.bursa_equities_history_2024q2 partition of dibots_v2.bursa_equities_history 
for values from ('2024-04-01') to ('2024-07-01');
create table dibots_v2.bursa_equities_history_2024q3 partition of dibots_v2.bursa_equities_history 
for values from ('2024-07-01') to ('2024-10-01');
create table dibots_v2.bursa_equities_history_2024q4 partition of dibots_v2.bursa_equities_history 
for values from ('2024-10-01') to ('2025-01-01');
create table dibots_v2.bursa_equities_history_2025q1 partition of dibots_v2.bursa_equities_history 
for values from ('2025-01-01') to ('2025-04-01');
create table dibots_v2.bursa_equities_history_2025q2 partition of dibots_v2.bursa_equities_history 
for values from ('2025-04-01') to ('2025-07-01');
create table dibots_v2.bursa_equities_history_2025q3 partition of dibots_v2.bursa_equities_history 
for values from ('2025-07-01') to ('2025-10-01');
create table dibots_v2.bursa_equities_history_2025q4 partition of dibots_v2.bursa_equities_history 
for values from ('2025-10-01') to ('2026-01-01');
create table dibots_v2.bursa_equities_history_default partition of dibots_v2.bursa_equities_history default;

select max(date) from dibots_v2.bursa_equities_history;

select * from dibots_v2.bursa_equities_history order by date desc

--2042
select count(distinct code) from dibots_v2.bursa_equities_history where date between (select max(date) from dibots_v2.bursa_equities_history) - interval '15 minutes' and
(select max(date) from dibots_v2.bursa_equities_history);

--2302
select count(*) from dibots_v2.exchange_daily_transaction where transaction_date = (select max(transaction_date) from dibots_v2.exchange_daily_transaction);

-- getting stock_code, board, sector
select stock_code, stock_name_short, board, sector from dibots_v2.exchange_daily_transaction where 
transaction_date = (select max(transaction_date) from dibots_v2.exchange_daily_transaction)

-- live stock board sector (not distinct, some board sector is null)
select a.code, b.stock_name_short, b.board, b.sector, a.chg, a.date from
(select code, chg, date from dibots_v2.bursa_equities_history where date between (select max(date) from dibots_v2.bursa_equities_history) - interval '15 minutes' and
(select max(date) from dibots_v2.bursa_equities_history)) a
left join 
(select stock_code, stock_name_short, board, sector from dibots_v2.exchange_daily_transaction where 
transaction_date = (select max(transaction_date) from dibots_v2.exchange_daily_transaction)) b
on a.code = b.stock_code
order by code;


-- getting only stock with today latest crawl
select code, max(date) from dibots_v2.bursa_equities_history
where date::date = current_date group by code;


-- stock and chg from the latest crawl (maybe create a view for this)
select a.code, a.last_done, a.lacp, a.chg, a.pct_chg, a.vol_00, a.buy_vol_00, a.buy, a.sell, a.sell_vol_00, a.high, a.low, a.date from
(select code, max(date) as max_date from dibots_v2.bursa_equities_history
where date::date = current_date group by code) latest
left join dibots_v2.bursa_equities_history a
on latest.code = a.code and latest.max_date = a.date;

drop view dibots_v2.stock_live_latest_view;

create or replace view dibots_v2.stock_live_latest_view as 
select a.code as stock_code, a.last_done, a.lacp, a.chg, a.pct_chg, a.vol_00, a.buy_vol_00, a.buy, a.sell, a.sell_vol_00, a.high, a.low, a.date from
(select code, max(date) as max_date from dibots_v2.bursa_equities_history
where date::date = current_date group by code) latest
left join dibots_v2.bursa_equities_history a
on latest.code = a.code and latest.max_date = a.date;

select * from dibots_v2.stock_live_latest_view;

-- board and sector 
select a.stock_code, b.board, b.sector, a.pct_chg, a.chg from dibots_v2.stock_live_latest_view a
left join dibots_v2.exchange_stock_profile b
on a.stock_code = b.stock_code and b.eff_end_date is null and b.delisted_date is null


-- by sector chg is positive
select c.sector, count(*) from (
select a.stock_code, b.board, b.sector, a.pct_chg, a.chg from dibots_v2.stock_live_latest_view a
left join dibots_v2.exchange_stock_profile b
on a.stock_code = b.stock_code and b.eff_end_date is null and b.delisted_date is null) c
where c.sector is not null and chg > 0
group by c.sector

-- klci
select count(*) from (
select a.stock_code, b.klci_flag, a.pct_chg, a.chg from dibots_v2.stock_live_latest_view a
left join dibots_v2.ref_demography_stock b
on a.stock_code = b.stock_code and b.trading_date = (select max(trading_date) from dibots_v2.ref_demography_stock)
where b.klci_flag = true) c
where chg > 0;



